services:
  dozzle:
    image: amir20/dozzle:latest
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      dozzle:
        condition: service_started
    expose:
      - 80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.logs-svc.rule=Host(`logs.piyushgarg.online`)'
      - 'traefik.http.services.logs-svc.loadbalancer.server.port=80'
      - 'traefik.http.routers.logs-svc.entrypoints=websecure'
      - 'traefik.docker.network=traefik-dozzle'
      - 'traefik.http.routers.logs-svc.tls=true'
      - 'traefik.http.routers.logs-svc.tls.certresolver=cert-resolver'
    networks:
      - internal
      - traefik-dozzle

networks:
  internal:
    driver: bridge
  traefik-dozzle:
    external: true
